## Automated Data Cleaning

##### Missing compleately at random (MCAR)
##### Missing at random (MAR)
##### Missing Not at random (MNAR)

In [95]:
import pandas as pd

df = pd.read_csv('unclean_smartwatch_health_data.csv')

df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [96]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 547.0 KB

In [97]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(400)

In [98]:
df[df['Heart Rate (BPM)'].isnull()==True]

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,3919.0,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,3945.0,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,2981.0,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,4099.0,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...,...
9875,NaN,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,1476.0,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,1434.0,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,4907.0,NaN,98.401058,3364.788855,5.691233932149209,Active,8

#### We have multiple option to clean data.
#### We can drop missing value data with dropna()
#### We can use Mean / Median Imputation to fill missing data with mean / meadian value.

In [99]:
df['Heart Rate (BPM)'].describe()

count    9600.000000
mean       76.035462
std        19.412483
min        40.000000
25%        64.890152
50%        75.220601
75%        85.198249
max       296.593970
Name: Heart Rate (BPM), dtype: float64

In [100]:
df['Heart Rate (BPM)'].median()

np.float64(75.22060125775644)

In [101]:
df['Heart Rate (BPM)'].mean()

np.float64(76.03546175646017)

In [102]:
df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].mean())

0        58.939776
1        76.035462
2       247.803052
3        40.000000
4        61.950165
           ...
9995     78.819386
9996     48.632659
9997     73.834442
9998     76.035462
9999     70.063864
Name: Heart Rate (BPM), Length: 10000, dtype: float64

## moving to make it permanent for 'Heart Rate BPM'

In [103]:
df['Heart Rate (BPM)']=df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].mean())

### checking isnull for that column

In [104]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(0)

In [105]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        10000 non-null  float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 547.0 KB

In [106]:
### now we have 10 thousand rows now
## drpping USERID columns with using columns drop

df=df.drop(columns=['User ID'])

In [107]:
## checking for other column
df['Blood Oxygen Level (%)'].isnull().sum()

np.int64(300)

In [108]:
## checking for True null value
df[df['Blood Oxygen Level (%)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
10,101.914938,NaN,2987.568640,7.541956463173237,Sedentary,9
21,68.310104,NaN,1058.374274,6.456918401449286,Actve,3
133,77.907578,NaN,15672.467752,9.079469571860296,Sedentary,10
134,78.227923,NaN,789.365922,3.5252990125882064,Seddentary,3
187,89.486636,NaN,2689.849911,5.737108446097524,Seddentary,6
...,...,...,...,...,...,...
9834,64.803112,NaN,1647.308449,8.04238137746177,Highly Active,7
9861,57.617790,NaN,14269.737149,6.390686112594759,Highly_Active,9
9885,75.281591,NaN,3852.160740,8.970316986352344,Actve,NaN
9905,87.693723,NaN,2364.028205,3.5490963940132865,Seddentary,3
9979,58.797407,NaN,359.210435,8.035879532058063,Active,5

In [109]:
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000             9700.000000   9900.000000
mean          76.035462               97.841581   6985.685885
std           19.020232                1.732863   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.662683   2021.039657
50%           76.035462               98.010642   4962.534599
75%           84.791711               99.376179   9724.902880
max          296.593970              100.000000  62486.690753

In [110]:
## checked values for Blood Oxygen Level (%) and filling with mean value
df['Blood Oxygen Level (%)'].mean()

np.float64(97.84158102099076)

In [111]:
df['Blood Oxygen Level (%)']=df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean())

In [112]:
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000            10000.000000   9900.000000
mean          76.035462               97.841581   6985.685885
std           19.020232                1.706669   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.703718   2021.039657
50%           76.035462               97.933416   4962.534599
75%           84.791711               99.327856   9724.902880
max          296.593970              100.000000  62486.690753

In [113]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [114]:
#df['Sleep Duration (hours)'].isnull==True
df[df['Step Count'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
136,70.593014,97.473981,NaN,3.439287691081752,Highly_Active,6
204,76.035462,98.710637,NaN,5.756958709255954,Highly_Active,8
603,69.084103,99.627473,NaN,6.358184719715759,Highly_Active,7
716,83.258294,98.704757,NaN,5.486240700986009,Seddentary,3
739,97.506420,97.651407,NaN,7.465981460156365,Active,6
...,...,...,...,...,...,...
9097,62.072133,96.810967,NaN,5.828570383973958,Seddentary,6
9121,54.793814,99.670176,NaN,6.686430627866978,Seddentary,2
9191,101.777396,100.000000,NaN,8.07989468005159,Active,10
9527,76.035462,94.694312,NaN,4.186856483292383,Seddentary,4
9565,90.411615,95.009355,NaN,8.582820460042822,Sedentary,4

In [ ]:
## fill value to user Forward fill or Backward fill
## like time series type of data
## in the case of Forward filling for example if 1 1 2 3 5 NaN 5 8 6 
## then 5 will fill on place NaN
## And for Backward NaN will changed with 5
## method --- ffill and bfill

## df['Step Count']=df['Step Count'].fillna(method='ffill')

## Note for Method : Your code uses fillna(method='ffill'). 
# In the environment tested, pandas is 3.1.0, 
# where fillna() no longer accepts method.
df["Step Count"] = df["Step Count"].ffill()

In [119]:
df["Step Count"].isnull().sum()

np.int64(0)