## Automated Data Cleaning

##### Missing compleately at random (MCAR)
##### Missing at random (MAR)
##### Missing Not at random (MNAR)

In [1090]:
import pandas as pd

df = pd.read_csv('unclean_smartwatch_health_data.csv')

df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [1091]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 547.0 KB

In [1092]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(400)

In [1093]:
df[df['Heart Rate (BPM)'].isnull()==True]

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,3919.0,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,3945.0,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,2981.0,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,4099.0,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...,...
9875,NaN,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,1476.0,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,1434.0,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,4907.0,NaN,98.401058,3364.788855,5.691233932149209,Active,8

#### We have multiple option to clean data.
#### We can drop missing value data with dropna()
#### We can use Mean / Median Imputation to fill missing data with mean / meadian value.

In [1094]:
df['Heart Rate (BPM)'].describe()

count    9600.000000
mean       76.035462
std        19.412483
min        40.000000
25%        64.890152
50%        75.220601
75%        85.198249
max       296.593970
Name: Heart Rate (BPM), dtype: float64

In [1095]:
df['Heart Rate (BPM)'].median()

np.float64(75.22060125775644)

In [1096]:
df['Heart Rate (BPM)'].mean()

np.float64(76.03546175646017)

In [1097]:
df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].mean())

0        58.939776
1        76.035462
2       247.803052
3        40.000000
4        61.950165
           ...
9995     78.819386
9996     48.632659
9997     73.834442
9998     76.035462
9999     70.063864
Name: Heart Rate (BPM), Length: 10000, dtype: float64

## moving to make it permanent for 'Heart Rate BPM'

In [1098]:
df['Heart Rate (BPM)']=df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].mean())

### checking isnull for that column

In [1099]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(0)

In [1100]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        10000 non-null  float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 547.0 KB

In [1101]:
### now we have 10 thousand rows now
## drpping USERID columns with using columns drop

df=df.drop(columns=['User ID'])

In [1102]:
## checking for other column
df['Blood Oxygen Level (%)'].isnull().sum()

np.int64(300)

In [1103]:
## checking for True null value
df[df['Blood Oxygen Level (%)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
10,101.914938,NaN,2987.568640,7.541956463173237,Sedentary,9
21,68.310104,NaN,1058.374274,6.456918401449286,Actve,3
133,77.907578,NaN,15672.467752,9.079469571860296,Sedentary,10
134,78.227923,NaN,789.365922,3.5252990125882064,Seddentary,3
187,89.486636,NaN,2689.849911,5.737108446097524,Seddentary,6
...,...,...,...,...,...,...
9834,64.803112,NaN,1647.308449,8.04238137746177,Highly Active,7
9861,57.617790,NaN,14269.737149,6.390686112594759,Highly_Active,9
9885,75.281591,NaN,3852.160740,8.970316986352344,Actve,NaN
9905,87.693723,NaN,2364.028205,3.5490963940132865,Seddentary,3
9979,58.797407,NaN,359.210435,8.035879532058063,Active,5

In [1104]:
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000             9700.000000   9900.000000
mean          76.035462               97.841581   6985.685885
std           19.020232                1.732863   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.662683   2021.039657
50%           76.035462               98.010642   4962.534599
75%           84.791711               99.376179   9724.902880
max          296.593970              100.000000  62486.690753

In [1105]:
## checked values for Blood Oxygen Level (%) and filling with mean value
df['Blood Oxygen Level (%)'].mean()

np.float64(97.84158102099076)

In [1106]:
df['Blood Oxygen Level (%)']=df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean())

In [1107]:
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000            10000.000000   9900.000000
mean          76.035462               97.841581   6985.685885
std           19.020232                1.706669   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.703718   2021.039657
50%           76.035462               97.933416   4962.534599
75%           84.791711               99.327856   9724.902880
max          296.593970              100.000000  62486.690753

In [1108]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [1109]:
#df['Sleep Duration (hours)'].isnull==True
df[df['Step Count'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
136,70.593014,97.473981,NaN,3.439287691081752,Highly_Active,6
204,76.035462,98.710637,NaN,5.756958709255954,Highly_Active,8
603,69.084103,99.627473,NaN,6.358184719715759,Highly_Active,7
716,83.258294,98.704757,NaN,5.486240700986009,Seddentary,3
739,97.506420,97.651407,NaN,7.465981460156365,Active,6
...,...,...,...,...,...,...
9097,62.072133,96.810967,NaN,5.828570383973958,Seddentary,6
9121,54.793814,99.670176,NaN,6.686430627866978,Seddentary,2
9191,101.777396,100.000000,NaN,8.07989468005159,Active,10
9527,76.035462,94.694312,NaN,4.186856483292383,Seddentary,4
9565,90.411615,95.009355,NaN,8.582820460042822,Sedentary,4

In [1110]:
## fill value to user Forward fill or Backward fill
## like time series type of data
## in the case of Forward filling for example if 1 1 2 3 5 NaN 5 8 6 
## then 5 will fill on place NaN
## And for Backward NaN will changed with 5
## method --- ffill and bfill

## df['Step Count']=df['Step Count'].fillna(method='ffill')

## Note for Method : Your code uses fillna(method='ffill'). 
# In the environment tested, pandas is 3.1.0, 
# where fillna() no longer accepts method.
df["Step Count"] = df["Step Count"].ffill()

In [1111]:
df["Step Count"].isnull().sum()

np.int64(0)

In [1112]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  9850 non-null   str
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(3), str(3)
memory usage: 468.9 KB

In [1113]:
df['Sleep Duration (hours)'].isnull().sum()

np.int64(150)

In [1114]:
df['Sleep Duration (hours)'].value_counts()

Sleep Duration (hours)
ERROR                 247
7.167235622316564       1
6.538239375570314       1
7.367789630207228       1
8.378342673824589       1
                     ...
7.402748595032027       1
6.3821659358529015      1
6.91654920303435        1
5.691233932149209       1
5.691001039740254       1
Name: count, Length: 9604, dtype: int64

In [1115]:
## checking ERROR values
df[df['Sleep Duration (hours)']=='ERROR']

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
2,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
62,115.078288,99.928041,1918.372142,ERROR,Highly_Active,4
71,64.799778,94.743857,4613.859266,ERROR,Highly_Active,10
81,41.709895,96.857347,1413.015778,ERROR,Highly_Active,4
92,70.243810,97.171134,2336.583406,ERROR,Highly Active,7
...,...,...,...,...,...,...
9901,63.369107,96.229029,6656.786482,ERROR,Active,4
9912,75.933666,97.386073,1813.072248,ERROR,Sedentary,10
9927,87.579045,98.768633,3727.161872,ERROR,Active,1
9943,91.834863,96.145378,38831.465057,ERROR,Active,4
9951,70.335328,98.560133,1997.442874,ERROR,Highly_Active,9

In [1116]:
## As checked count of ERROR is 247
## convert data type to numeric format, using to_numeric of padas
df['Sleep Duration (hours)']=pd.to_numeric(df['Sleep Duration (hours)'],errors='coerce')

In [1117]:
## cecking again after change datatype to numeric
## checking ERROR values
df[df['Sleep Duration (hours)']=='ERROR']

Empty DataFrame
Columns: [Heart Rate (BPM), Blood Oxygen Level (%), Step Count, Sleep Duration (hours), Activity Level, Stress Level]
Index: []

In [1118]:
## now it's 0
## so will check values isnull and values cout
df['Sleep Duration (hours)'].isnull().sum()

np.int64(397)

In [1119]:
## checking where isnull is True
df[df['Sleep Duration (hours)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
2,247.803052,97.052954,2826.521994,NaN,Highly Active,5
4,61.950165,98.583797,15679.067648,NaN,Highly_Active,6
33,80.243365,100.000000,6848.558834,NaN,Sedentary,6
62,115.078288,99.928041,1918.372142,NaN,Highly_Active,4
71,64.799778,94.743857,4613.859266,NaN,Highly_Active,10
...,...,...,...,...,...,...
9901,63.369107,96.229029,6656.786482,NaN,Active,4
9912,75.933666,97.386073,1813.072248,NaN,Sedentary,10
9927,87.579045,98.768633,3727.161872,NaN,Active,1
9943,91.834863,96.145378,38831.465057,NaN,Active,4
9951,70.335328,98.560133,1997.442874,NaN,Highly_Active,9

In [1120]:
## checking datatype
df['Sleep Duration (hours)'].dtype

dtype('float64')

In [1121]:
df['Sleep Duration (hours)']

0       7.167236
1       6.538239
2            NaN
3       7.367790
4            NaN
          ...
9995    7.402749
9996    6.382166
9997    6.916549
9998    5.691234
9999    5.691001
Name: Sleep Duration (hours), Length: 10000, dtype: float64

In [1122]:
## checking mean and median, to fill NaN with any of this
df['Sleep Duration (hours)'].mean()

np.float64(6.505462918406444)

In [1123]:
## median
df['Sleep Duration (hours)'].median()

np.float64(6.503308362112644)

In [1124]:
## checking is null values
df['Sleep Duration (hours)'].isnull().sum()

np.int64(397)

In [1125]:
## filling isnull NaN with mean
df['Sleep Duration (hours)']=df['Sleep Duration (hours)'].fillna(df['Sleep Duration (hours)'].mean())

In [1126]:
## checking dfinfo
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(4), str(2)
memory usage: 468.9 KB

In [1127]:
## again checking if NaN exist
df['Sleep Duration (hours)'].isnull().sum()

np.int64(0)

In [1128]:
df.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167236,Highly Active,1
1,76.035462,98.532195,727.601610,6.538239,Highly_Active,5
2,247.803052,97.052954,2826.521994,6.505463,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367790,Actve,3
4,61.950165,98.583797,15679.067648,6.505463,Highly_Active,6

In [1129]:
## working for categorical column
## For this using mode ---> most frequent repeting value in column
df['Activity Level'].mode()

0    Seddentary
Name: Activity Level, dtype: str

In [1130]:
df['Activity Level'].isnull().sum()

np.int64(200)

In [1131]:
## Seddentary is beign used most frequently for Activity Level
df['Activity Level']=df['Activity Level'].fillna('Seddentary')

In [1132]:
## it was 200 no checking again
df['Activity Level'].isnull().sum()

np.int64(0)

In [1133]:
## checking df info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            9800 non-null   str
dtypes: float64(4), str(2)
memory usage: 468.9 KB

In [1134]:
## Constant Imputation : To fill missing value with the constant or sentinel value.. like unknown or any
# checking for Stress LEvel
df['Stress Level'].isnull().sum()

np.int64(200)

In [1135]:
df['Stress Level']

0       1
1       5
2       5
3       3
4       6
       ..
9995    7
9996    2
9997    4
9998    8
9999    5
Name: Stress Level, Length: 10000, dtype: str

In [1136]:
df[df['Stress Level'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
13,79.062632,99.014913,829.925623,6.269060,Sedentary,NaN
22,81.267235,96.068161,10503.006243,5.780212,Actve,NaN
45,87.135918,97.708276,3437.285884,5.945493,Highly_Active,NaN
179,68.809496,99.268945,6254.337835,7.125259,Sedentary,NaN
261,74.268839,97.905483,4333.083235,9.553164,Seddentary,NaN
...,...,...,...,...,...,...
9776,76.035462,95.867583,3056.367782,6.177411,Actve,NaN
9826,55.151993,99.312648,40.324128,8.376416,Highly_Active,NaN
9868,76.035462,100.000000,12493.577435,3.641176,Seddentary,NaN
9873,43.889444,95.345083,12980.404669,7.140447,Seddentary,NaN
9885,75.281591,97.841581,3852.160740,8.970317,Actve,NaN

In [1137]:
df['Stress Level'].value_counts()

Stress Level
2            1007
7            1006
6            1001
3             995
1             984
9             976
4             966
10            954
5             945
8             917
Very High      49
Name: count, dtype: int64

In [1138]:
## this is an string data type , so updating it with any constant value
## as per values_count it's showing VEry High count is 49
df['Stress Level']=df['Stress Level'].fillna('Unknown')

In [1139]:
## now checking df.info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  str
dtypes: float64(4), str(2)
memory usage: 468.9 KB

In [1140]:
## looks all have values now
## test for Simple Imputation
## reloading csv
## and will fill using import SimpleImputer

from sklearn.impute import  SimpleImputer

csv = pd.read_csv('unclean_smartwatch_health_data.csv')

csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   str
 5   Activity Level          9800 non-null   str
 6   Stress Level            9800 non-null   str
dtypes: float64(4), str(3)
memory usage: 547.0 KB

In [1141]:
csv=csv.drop(columns=['User ID'])
## removed column

In [1142]:
df.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167236,Highly Active,1
1,76.035462,98.532195,727.601610,6.538239,Highly_Active,5
2,247.803052,97.052954,2826.521994,6.505463,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367790,Actve,3
4,61.950165,98.583797,15679.067648,6.505463,Highly_Active,6

In [1143]:
csv['Sleep Duration (hours)']=pd.to_numeric(csv['Sleep Duration (hours)'],errors='coerce')

In [1144]:
csv[csv['Sleep Duration (hours)']=='ERROR']

Empty DataFrame
Columns: [Heart Rate (BPM), Blood Oxygen Level (%), Step Count, Sleep Duration (hours), Activity Level, Stress Level]
Index: []

In [1145]:
## no any ERROR value now.
csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        9600 non-null   float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9603 non-null   float64
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(4), str(2)
memory usage: 468.9 KB

In [1146]:
## fillling for Hear Rate (BPM)
## fillling for Blood Oxygen Level (%)

csv.describe()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours)
count,9600.000000,9700.000000,9900.000000,9603.000000
mean,76.035462,97.841581,6985.685885,6.505463
std,19.412483,1.732863,6885.809680,1.510029
min,40.000000,90.791208,0.910138,-0.194453
25%,64.890152,96.662683,2021.039657,5.493820
50%,75.220601,98.010642,4962.534599,6.503308
75%,85.198249,99.376179,9724.902880,7.529357
max,296.593970,100.000000,62486.690753,12.140233

In [1147]:
csv.isnull()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,False,False,False,False,False,False
1,True,False,False,False,False,False
2,False,False,False,True,False,False
3,False,False,False,False,False,False
4,False,False,False,True,False,False
...,...,...,...,...,...,...
9995,False,False,False,False,False,False
9996,False,False,False,False,False,False
9997,False,False,False,False,False,False
9998,True,False,False,False,False,False
9999,False,False,False,False,False,False

In [1148]:
csv[csv.isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
9995,NaN,NaN,NaN,NaN,NaN,NaN
9996,NaN,NaN,NaN,NaN,NaN,NaN
9997,NaN,NaN,NaN,NaN,NaN,NaN
9998,NaN,NaN,NaN,NaN,NaN,NaN
9999,NaN,NaN,NaN,NaN,NaN,NaN

In [1149]:
csv['Heart Rate (BPM)'].mean()

np.float64(76.03546175646017)

In [1150]:
csv['Heart Rate (BPM)'].median()

np.float64(75.22060125775644)

In [1151]:
## using strategy to median
## and fill value with fit_transform to mean/median
## and using ravel() to change 2D
imputer=SimpleImputer(strategy='median')
csv['Heart Rate (BPM)']=imputer.fit_transform(csv[['Heart Rate (BPM)']]).ravel()

In [1152]:
## after fixing Heart Rate (BPM) checking info
csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9603 non-null   float64
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(4), str(2)
memory usage: 468.9 KB

In [1153]:
## that is fixed now
csv['Blood Oxygen Level (%)'].isnull().sum()
imputer=SimpleImputer(strategy='mean')
csv['Blood Oxygen Level (%)']=imputer.fit_transform(csv[['Blood Oxygen Level (%)']]).ravel()
csv['Step Count']=imputer.fit_transform(csv[['Step Count']]).ravel()

In [1154]:
## after fixing Blood Oxygen Level (%) checking info
csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  9603 non-null   float64
 4   Activity Level          9800 non-null   str
 5   Stress Level            9800 non-null   str
dtypes: float64(4), str(2)
memory usage: 468.9 KB

In [1155]:
csv.describe()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours)
count,10000.000000,10000.000000,10000.000000,9603.000000
mean,76.002867,97.841581,6985.685885,6.505463
std,19.020902,1.706669,6851.290665,1.510029
min,40.000000,90.791208,0.910138,-0.194453
25%,65.322796,96.703718,2037.300857,5.493820
50%,75.220601,97.933416,5023.631772,6.503308
75%,84.791711,99.327856,9680.097095,7.529357
max,296.593970,100.000000,62486.690753,12.140233

In [1156]:
## this Blood Oxygen Level (%) is fixed now
## Activity and Stree Level is categorical column
csv['Stress Level'].isnull().sum()

np.int64(200)

In [1157]:
## using most frequest value to fill missing data
imputer=SimpleImputer(strategy='most_frequent')
csv['Stress Level']=imputer.fit_transform(csv[['Stress Level']]).ravel()

In [1158]:
## After fixing this categorical columns checking info of dataframe
csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  9603 non-null   float64
 4   Activity Level          9800 non-null   str
 5   Stress Level            10000 non-null  str
dtypes: float64(4), str(2)
memory usage: 468.9 KB

In [1159]:
csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  9603 non-null   float64
 4   Activity Level          9800 non-null   str
 5   Stress Level            10000 non-null  str
dtypes: float64(4), str(2)
memory usage: 468.9 KB

In [1160]:
csv['Sleep Duration (hours)'].value_counts()

Sleep Duration (hours)
7.167236    1
6.538239    1
7.367790    1
8.378343    1
7.871146    1
           ..
7.402749    1
6.382166    1
6.916549    1
5.691234    1
5.691001    1
Name: count, Length: 9603, dtype: int64

In [1161]:
#imputer=SimpleImputer(strategy='constant',fill_value='unknown')
#csv['Sleep Duration (hours)']=imputer.fit_transform(csv[['Sleep Duration (hours)']]).ravel()

In [1162]:
imputer=SimpleImputer(strategy='most_frequent')
csv['Activity Level']=imputer.fit_transform(csv[['Activity Level']]).ravel()

In [1163]:
csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  9603 non-null   float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  str
dtypes: float64(4), str(2)
memory usage: 468.9 KB

In [1164]:
csv.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167236,Highly Active,1
1,75.220601,98.532195,727.601610,6.538239,Highly_Active,5
2,247.803052,97.052954,2826.521994,NaN,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367790,Actve,3
4,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [1165]:
csv['Sleep Duration (hours)'].mean()

np.float64(6.505462918406444)

In [1166]:
csv['Sleep Duration (hours)'].median()

np.float64(6.503308362112644)

In [1167]:
imputer=SimpleImputer(strategy='median')
csv['Sleep Duration (hours)']=imputer.fit_transform(csv[['Sleep Duration (hours)']]).ravel()

In [1168]:
## checking after cleaning data csv
csv.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  str
 5   Stress Level            10000 non-null  str
dtypes: float64(4), str(2)
memory usage: 468.9 KB

In [1169]:
csv['Heart Rate (BPM)'].value_counts()

Heart Rate (BPM)
75.220601     400
40.000000      84
58.939776       1
247.803052      1
61.950165       1
             ...
77.912299       1
78.819386       1
48.632659       1
73.834442       1
70.063864       1
Name: count, Length: 9518, dtype: int64